"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[ $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$gcloud\
[ ](fg:#212736)\
$fill\
$cmd_duration\
[ ](fg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character
"""

# right_format = """
# $time
# """

[os]
format = "$symbol"
disabled = false
[os.symbols]
Macos = " "
Ubuntu = " "

[directory]
style = "fg:#050505 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰌾"                 #鍵のicon
home_symbol = ' ~'             # nf-fa-home

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[fill]
symbol = '─'
style = 'blue'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ [$symbol](fg:#E56C2B bg:#212736) ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[gcloud]
format = '[ $symbol$account(@$domain)(\($project\))]($style) '

[cmd_duration]
format = "[󰔟 $duration]($style)"
show_milliseconds = true

[time]
disabled = false
time_format = "%T"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
