[starship]
"starship.toml" = ".config/starship.toml"

[sheldon]
"plugins.toml" = ".config/sheldon/plugins.toml"
"scripts/" = ".config/sheldon/scripts"

[zsh]
".zshrc" = ".zshrc"
".zshenv" = ".zshenv"

[colima]
"_templates/default.yaml" = "~/.colima/_templates/default.yaml"

[kitty]
"kitty.conf" = "~/.config/kitty/kitty.conf"

[docker]
"config.json" = "~/.docker/config.json"
